base:
  project:qualitywine.project
  random_state:42
  target_col:TARGET

data_source:
  s3_source:data_given\qualitywine.csv

load_data:
  row_dataset_csv: data\row\qualitywine.csv

split_data:
  train_path: data\processed\train_qualitywine.csv
  test_path: data\processed\test_qualitywine.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha:0.88
      l1_ratio: 0.89

model_dir: saved_models

